spring:
  jpa:
    hibernate:
      ddl-auto: update
      show-sql: false
  datasource:
    url: jdbc:mysql://localhost:3306/loja_livro?createDatabaseIfNotExist=true
    username: root
    password: root
  jackson:
    default-property-inclusion: non_null